cmake_minimum_required(VERSION 3.24)
include(.cmake.conf)
project(QtTestSupport VERSION 6.11.1 LANGUAGES C CXX)
find_package(Qt6 ${PROJECT_VERSION} CONFIG REQUIRED COMPONENTS BuildInternals)
qt_internal_project_setup()
find_package(Qt6 ${PROJECT_VERSION} CONFIG REQUIRED COMPONENTS Core CorePrivate)
qt_build_repo_begin()
add_subdirectory("${QTBASE_TEST_SOURCE}/src/testlib" testlib)
qt_build_repo_post_process()
qt_build_repo_end()
